"""PlanIndexRenderer — pure function from records to PLAN_INDEX.md string.

Emits the staleness-header so humans reading the rendered artifact
know when it was last generated. The renderer is pure (no I/O); the
writer module handles disk writes.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from mahavishnu.plan_index.types import PlanRecordDict

__all__ = ["render"]


def render(records: list[PlanRecordDict]) -> str:
    """Render PLAN_INDEX.md markdown. Pure function."""
    now_iso = datetime.now(tz=UTC).isoformat(timespec="seconds")
    lines: list[str] = []

    # Staleness-header — emitted so humans know when the render was generated.
    # (Spec §D5: humans reading the cached PLAN_INDEX.md need to know it's stale.)
    lines.append(
        f"<!-- Last regenerated: {now_iso} UTC · "
        "run mcp__mahavishnu__plan_rebuild_status for staleness check -->"
    )
    lines.append("")
    lines.append("# Plan Index")
    lines.append("")
    lines.append(f"**Last regenerated:** {now_iso} UTC")
    lines.append(
        "**Purpose:** Navigation map for Mahavishnu/Bodai plans. "
        "Generated by `scripts/regenerate_plan_index.py`. Do not edit by hand."
    )
    lines.append("")

    if not records:
        lines.append("No plans indexed.")
        lines.append("")
        return "\n".join(lines)

    # Sort by date DESC then path ASC (matches the existing PLAN_INDEX.md convention).
    sorted_records = sorted(
        records, key=lambda r: (r["date"], r["path"]), reverse=True
    )

    lines.append("## Plans")
    lines.append("")
    lines.append("| Date | Path | Title | Status | Role | Topic | Plan ID |")
    lines.append("|---|---|---|---|---|---|---|")
    for r in sorted_records:
        lines.append(
            f"| {r['date']} | {r['path']} | {r['title']} | {r['status']} "
            f"| {r['role']} | {r['topic']} | `{r['plan_id'][:8]}` |"
        )
    lines.append("")
    lines.append(f"**Total:** {len(records)} plans")
    lines.append("")
    return "\n".join(lines)
